### PR TITLE
feat: verify kmod signatures for dual-sign

### PR DESCRIPTION
**Pull request by m2Giles**
## Thank you for contributing to the Universal Blue project!

Please [read the Contributor's Guide](https://universal-blue.org/contributing.html) before submitting a pull request.

### CODE REVIEW

**Comment by m2Giles** [comment]
This checks during build stage and not in the final rpms.

**Comment by m2Giles** [comment]
To build another container to test the rpms would likely have a longer build time than the actual akmods build.

So not sure what the best method for ensuring the RPMs that are copied into the scratch container are indeed dual signed.

**Comment by m2Giles** [comment]
Went and made a test container that is built after the akmods is built. It installs the kernel and the signed rpms, and then checks the signatures. It can handle both dual signed and single signed. It will stop a push if the the akmods are not signed correctly.

**Review by KyleGospo — APPROVED** [review]

**Review by bsherman — APPROVED** [review]
Beautiful

**Pull request merged**
