### PR TITLE
chore: refactor package rename script to support all kernel versions

### PR DESCRIPTION
**Pull request by p5**
Updates the RPM renaming script to read the kernel version from the installed kernel-core RPM, removing that string from the package names if it exists.

### CODE REVIEW

**Comment by bsherman** [comment]
@p5 confirming I understand the purpose here.

This keeps the same general behavior as before, but is safe for future kernel versions. 
Plus, it eliminates reprocessing of any RPM packages which don't have kernel-version in the package name.

Correct?

**Comment by p5** [comment]
> This keeps the same general behavior as before, but is safe for future kernel versions.
Plus, it eliminates reprocessing of any RPM packages which don't have kernel-version in the package name.


Exactly.  If it worked.  
For some reason, it does not as builds are failing

**Comment by antheas** [comment]
I would suggest gutting the logic and just checking if -6 exists in the string and only doing the sub then. Much simpler for now.

**Comment by bsherman** [comment]
> Exactly. If it worked. For some reason, some builds are failing.

I did some "println debugging" and saw this:
```
KERNEL_VERSION=6.11.3-200.fc40.x86_64
BASENAME=kmod-xpadneo-6.11.3-200.fc40.x86_64-0.9.6^20240923git70ef8ee-3.fc40.x86_64.rpm
OLD_NAME=kmod-xpadneo
P5_NAME=kmod-xpadneo-0.9.6^20240923git70ef8ee-3.fc40.x86_64.rpm
NEW_NAME=kmod-xpadneo
REBUILDING kmod-xpadneo-6.11.3-200.fc40.x86_64-0.9.6^20240923git70ef8ee-3.fc40.x86_64.rpm as it DOES contain 6.11.3-200.fc40.x86_64 in its name
```

The `sed` command simply wasn't behaving in a manner similar to the old bash native substitution... 

I'll push a fix momentarily.

**Review by bsherman — APPROVED** [review]
Not only does this make this work for future kernels, this fixes an issue where we were incorrectly renaming RPMs which did NOT have the kernel string in their filename. (eg, ZFS library RPMs).

**Review by HikariKnight — APPROVED** [review]

**Pull request merged**
