### PR TITLE
feat: add Rok CDEmu for including vhba kmod

### PR DESCRIPTION
**Pull request by RodoMa92**

### CODE REVIEW

**Comment by bsherman** [comment]
@RodoMa92 Hello and thanks for the PR.

I'm not familiar with any history regarding a request to add this kmod to ublue.  Was there a Discord discussion to which you can direct me? I don't see an issue requesting it.

Thank you.

**Comment by RodoMa92** [comment]
> @RodoMa92 Hello and thanks for the PR.
> 
> I'm not familiar with any history regarding a request to add this kmod to ublue.  Was there a Discord discussion to which you can direct me? I don't see an issue requesting it.
> 
> Thank you.

If you search for cdemu in the bazzite discord channel there is some hits regarding people who tried to ask for guidance on installing this program. This kmod is a prerequisite to make it work.

I've also opened an issue on the bazzite repo requesting to being included in, if you want more info on what it can do.

**Comment by bsherman** [comment]
> If you search for cdemu in the bazzite discord channel there is some hits regarding people who tried to ask for guidance on installing this program. This kmod is a prerequisite to make it work.
> 
> I've also opened an issue on the bazzite repo requesting to being included in, if you want more info on what it can do. The issue is this: [ublue-os/bazzite#919](https://github.com/ublue-os/bazzite/issues/919)

Perfect! Thank you for the link to the issue and the bigger context.

**Review by KyleGospo — APPROVED** [review]

**Comment by KyleGospo** [comment]
@RodoMa92 Went to approve this, but running into:
`error: Packages not found: akmod-vhba-*.fc40.x86_64`

**Review by bsherman — APPROVED** [review]

**Comment by bsherman** [comment]
Approved and direct merged. Will do full rebuild later.

**Pull request merged**
