### PR TITLE
chore: Add version 550 of the Nvidia module

### PR DESCRIPTION
**Pull request by dylanmtaylor**

### CODE REVIEW

**Review by bsherman — CHANGES_REQUESTED** [review]
Echoing my comment on https://github.com/ublue-os/nvidia/pull/196#pullrequestreview-1888828715

Note: rpmfusion usually removes the previous "current" very quickly after publishing the new one. So in reality, we'll probably need to replace 545 with 550, rather than only add 550.


Plus, the `exclude:` section must be updated here.... If we replace 545 with 550, the exclude section must also change. If we add, there must be a new section excluding common/550.

**Review by bsherman — APPROVED** [review]
looks good now

**Comment by fiftydinar** [comment]
Update the README too

**Comment by dylanmtaylor** [comment]
On a personal note, I'm so excited to get the 550 driver on my Nvidia systems as I'm experiencing a bunch of flickering and bugginess on 545 and this one supposedly improves the situation. :)

**Comment by bsherman** [comment]
> [akmod-nvidia-550.54.14-1.fc39.x86_64.rpm](https://fedora.pkgs.org/39/rpmfusion-nonfree-updates-testing-x86_64/akmod-nvidia-550.54.14-1.fc39.x86_64.rpm.html) looks to be published.

Doesn't look like mirrors have actually picked this up yet, specifically the mirror we use: https://mirror.fcix.net/rpmfusion/nonfree/fedora/updates/39/x86_64/a/

**Comment by dylanmtaylor** [comment]
> > [akmod-nvidia-550.54.14-1.fc39.x86_64.rpm](https://fedora.pkgs.org/39/rpmfusion-nonfree-updates-testing-x86_64/akmod-nvidia-550.54.14-1.fc39.x86_64.rpm.html) looks to be published.
> 
> Doesn't look like mirrors have actually picked this up yet, specifically the mirror we use: https://mirror.fcix.net/rpmfusion/nonfree/fedora/updates/39/x86_64/a/

Oh, I see it is in the -testing repo not the regular one. I guess we may have to wait a few days for it to be promoted.

**Comment by dylanmtaylor** [comment]
I doubt we're okay with using -testing for now even though it is a stable driver version...

**Review by p5 — APPROVED** [review]

**Comment by dylanmtaylor** [comment]
Awesome to see this finally going in! :)

**Pull request merged**
