### PR TITLE
feat: add 'extra' akmod stream & facetimehd-kmod to akmod cache

### PR DESCRIPTION
**Pull request by mulderje**
Copying the below from #158 which was auto-closed/merged since I didn't make the PR from a branch and main got synced. Wanted to also quickly confirm that `podman build -f Containerfile.common .` works locally with this PR, and appears to add in the `facetimehd-kmod` RPM.

I have been working on getting an old MacBook Air fully running, and running into things like not being able to just copy firmware files into the base system... :) 

One thing missing within the Fedora repos for me was the [FacetimeHD Firmware](https://github.com/patjak/facetimehd/). This led me down a path of creating the below. Please note this was my first time messing around with spec files/copr, and any feedback/suggestions would be much appreciated.

1. [Spec files](https://github.com/mulderje/facetimehd-kmod-rpm) can be found here.
2. [COPR](https://copr.fedorainfracloud.org/coprs/mulderje/facetimehd-kmod/). Note: I can leverage this to add to my machine locally now via adding the copr and `sudo rpm-ostree install akmod-facetimehd facetimehd-firmware`, which is already a huge improvement
3. I would like to figure out how to get the automated builds working with something like [Blue build](https://github.com/mulderje/ublue-oldair). Note: this is currently [failing builds with e.g. permission issues](https://github.com/mulderje/ublue-oldair/actions/runs/8502256499/job/23286202050#step:2:1641)

Open questions:

- Would you want this to be included here in your main akmod repo or is this too niche?
- If you would like here, would you also like included in your [COPR](https://copr.fedorainfracloud.org/coprs/ublue-os/akmods/) vs [2] above?
- If no, any suggestions or recommendations for the spec [1]/copr [2] setup to help get [3] working?
- Are there any best practices that I should be following with things like packit, bohdi, koji, etc.? It looks like there are a few things that I need to do to make sure things stay up to date, but would love to plug into something you have if possible.

Thanks!
Jon

### CODE REVIEW

**Comment by mulderje** [comment]
PR in my fork passes all builds for f39. https://github.com/mulderje/akmods/actions/runs/8573353338?pr=5

**Comment by bsherman** [comment]
One best practice, please don't force push, especially once feedback starts getting added to the PR. :-)  It causes the loss of context.

**Comment by mulderje** [comment]
Good to know. I was having issues cleaning up some small commits and ended up doing something like `git rebase -i HEAD~3` and then needing to do a `git push --force` to get it to go into github. Is there a way to do that cleanly? 

Likewise when updating my fork is there a preferred git incantation to keep things merged/rebased?

E.g. for this pr to pull in your updated, what would you do to update the branch/pr code? I had tried to do a sync in the UI then pull/rebase into my branch but it looks like that's not ideal either based on the way it showed up in the logs.

**Comment by mulderje** [comment]
Is there a way to re-kick the builds here? Looks like I had some failures due to the v4l2loopback module you are debugging.

**Comment by bsherman** [comment]
> Is there a way to re-kick the builds here? Looks like I had some failures due to the v4l2loopback module you are debugging.

You just did it! I approved another build attempt.

**Comment by mulderje** [comment]
FYI rebased this against #171 

Build is successful in my fork at mulderje/akmods#5

**Review by KyleGospo — APPROVED** [review]

**Comment by bsherman** [comment]
Closes: #176

**Review by m2Giles — APPROVED** [review]

**Review by bsherman — APPROVED** [review]
LGTM

**Pull request merged**
