### PR TITLE
chore: Restore negativo17 on Fedora 39

### PR DESCRIPTION
**Pull request by KyleGospo**
Repos exist now, merge me when I build properly

### CODE REVIEW

**Comment by bsherman** [comment]
@EyeCantCU mostly completed this PR with the changes in #79 

I think `evdi` is still outstanding.

**Comment by bsherman** [comment]
@KyleGospo do you not want `evdi` ? it's still not building on F39... it's just a conditional, not sure if its working in the negativo17 upstream or not

**Comment by KyleGospo** [comment]
> @KyleGospo do you not want `evdi` ? it's still not building on F39... it's just a conditional, not sure if its working in the negativo17 upstream or not

Reopened, quicker than fixing the merge conflict here given how tiny of a change it is.

**Comment by bsherman** [comment]
Linking for reference: https://github.com/ublue-os/akmods/pull/86

**Pull request closed without merging**
