### PR TITLE
feat: Add Google Coral TPU driver (gasket & apex) akmod

### PR DESCRIPTION
**Pull request by KyleGospo**
Driver needed for Google's Coral TPU hardware on Linux, useful for home servers since it can do ML image processing at very low power usage.

https://coral.ai/products/

Version actually being built here is at https://github.com/KyleGospo/gasket-dkms
We could build upstream, however it has issues preventing it from being unloaded and a few other bugs fixed downstream at OpenSUSE among other places, so this repo serves as a patched source.

### CODE REVIEW

**Comment by bsherman** [comment]
More general question, since I've been away and missed some things.

Are we now building a variety of akmod kmod RPMs in this repo even if they aren't included in `main`? This seems to be the case given `main` is now more restrictive about which akmod RPMs are installed.

**Comment by KyleGospo** [comment]
That's correct, that wasn't my initial intent but we got an issue on main asking why steam deck drivers were included and why they couldn't remove them, so perhaps letting this be a repo for all akmods and letting downstream pull any additional ones they want would be best.

**Review by bsherman — CHANGES_REQUESTED** [review]
My minor change request to README

I 'm  just trying to think of some consistent way to show from where we get 1) the source (project repo) 2) the rpms (eg, copr, negativo17) if not from rpmfusion

**Comment by KyleGospo** [comment]
Closing to clean up commit history and make requested changes

**Pull request closed without merging**
