### PR TITLE
fix(framework-laptop): ensure only in one kmod stream

### PR DESCRIPTION
**Pull request by mulderje**
The framework-laptop kmod should only be in extra, but I accidentally put it in both extra and common. No functionality changes expected to the extra package, but will remove framework-laptop from common.

Breaking this out from #177 while that goes through review so it can get cleaned up.

### CODE REVIEW

**Comment by m2Giles** [comment]
This should be common. However, it isn't quite ready so we are not including in bluefin yet.

**Comment by mulderje** [comment]
> This should be common. However, it isn't quite ready so we are not including in bluefin yet.

I'm totally fine with common or extra. My goal here is to fix the bug of the kmod being in both right now, and defaulted to what was previously agreed upon. If that's the consensus now I'm happy to switch this PR to common only. Please let me know!

**Comment by mulderje** [comment]
Given the recent announcements and what @m2Giles mentioned above, changing this to common vs extra. I would like to get a version of this reviewed sooner vs later as `framework-laptop` is currently being built in both common and extra.

**Review by bsherman — APPROVED** [review]
Looks good

**Review by castrojo — APPROVED** [review]

**Pull request merged**
