### PR TITLE
chore: enable Fedora 41 builds

### PR DESCRIPTION
**Pull request by p5**
Status, even after we merge this PR can be found at: #248

### CODE REVIEW

**Comment by bsherman** [comment]
@p5  

`common` build failures:
-  `xpadneo` ... it's not yet available for F41. We could conditionally not build that as a temporarly workaround.

`extra` build failures:
- `zenergy` fails on kernel 6.11.1 ... i'm not sure why

`nvidia` build failures:
- looks like the F41 rpmbuild issue with @m2Giles has addressed elsewhere... can you take a look? https://github.com/ublue-os/akmods/actions/runs/11205646915/job/31145409774#step:12:1580

**Comment by m2Giles** [comment]
For the nvidia issues, we need to do the same as what we did in kernel-cache. Add a symlink and specify the symlink as the build-root.

https://github.com/ublue-os/kernel-cache/blob/a768ce0a789a638f05746dcad46735197597735b/fetch.sh#L157

https://github.com/ublue-os/kernel-cache/blob/a768ce0a789a638f05746dcad46735197597735b/fetch.sh#L170

**Comment by bsherman** [comment]
> For the nvidia issues, we need to do the same as what we did in kernel-cache. Add a symlink and specify the symlink as the build-root.
> 
> https://github.com/ublue-os/kernel-cache/blob/a768ce0a789a638f05746dcad46735197597735b/fetch.sh#L157
> 
> https://github.com/ublue-os/kernel-cache/blob/a768ce0a789a638f05746dcad46735197597735b/fetch.sh#L170

I can do this, thank you .

**Comment by m2Giles** [comment]
I just did it.

**Comment by bsherman** [comment]
> I just did it.

even better! thank you!

**Comment by m2Giles** [comment]
Looks like nvidia is now working for F41.

We are only caching kernels for asus and main right now. There is no F41 of surface, fsync, and coreos yet.

**Comment by m2Giles** [comment]
Not sure why evdi doesn't have the kmod in repo yet at least that's what the error looks like.

**Comment by bsherman** [comment]
> Not sure why evdi doesn't have the kmod in repo yet at least that's what the error looks like.

It's there, but I noticed something similar to this in bluefin when I was converting to support negativo17... sometimes the package providing the "foo-kmod-common" doesn't resolve properly. Thus in bluefin we now specify an extra package with the kmod install.

I think we need to do the same here

**Comment by bsherman** [comment]
@p5 @m2Giles @KyleGospo 

I think this is probably ready for review to at least start building F41 akmods images.

Caveats are 4 kmods not building yet and those are documented in #248

**Review by m2Giles — APPROVED** [review]

**Review by bsherman — APPROVED** [review]

**Review by KyleGospo — APPROVED** [review]

**Pull request merged**
